apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: giropops-2
spec:
  containers:
  - image: nginx
    name: giropops
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: giropops
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: giropops
  type: NodePort
status:
  loadBalancer: {}
